Download libraries

In [16]:
import sys
import os
import time
import csv

In [70]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

/Users/imacair/anaconda/lib/python2.7/site-packages/nltk/twitter/__init__.py:20: UserWarning: The twython library has not been installed. Some functionality from the twitter package will not be available.
  warnings.warn("The twython library has not been installed. "


In [3]:
import pandas as pd
import numpy as np

In [4]:
from sklearn.cross_validation import train_test_split
import numpy as np

/Users/imacair/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [5]:

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import svm
from sklearn.metrics import classification_report

Set working directory

In [6]:
print os.getcwd();

/Users/imacair


Reads the file

In [7]:
os.chdir("/Users/imacair/Desktop/Products3/")

In [8]:
data = pd.read_csv('Final_Manual_0805.csv', encoding= "latin-1",delimiter=',',low_memory=False)

In [9]:
#Converts text into ASCII
data.message = data.message.str.encode('ascii','replace')
data.sentiment = data.sentiment.str.encode('utf-8','replace')


In [10]:
len(data)

965

Take a sample from data

In [11]:
data_t=data["message"]

In [12]:
#lowercase before abbriviation translation
data_t = data_t.str.lower()

In [13]:
#takes sentiment
data_s=data["sentiment"]

Preprocess the data

Replacement of abbriviations

In [17]:
with open('abbrev.csv', mode='r') as infile:
    reader = csv.reader(infile)
    replacement = {rows[0].lower():rows[1].lower() for rows in reader              
                  }

In [18]:
##How in works
s1 = 'y r u l8'

s2 = ' '.join([replacement.get(w, w) for w in s1.split()])
s2

'why? -or- yes are you l8'

In [19]:
result = pd.DataFrame()
result = data_t

In [20]:
for i in range(len(result)):
    data_t.values[i]=' '.join([replacement.get(w, w) for w in data_t.values[i].split()])

In [22]:
data_t.head()

0    #llbite ankylosing spondylitis - have (in date...
1    #as 3 things people with ankylosing spondyliti...
2    working group on the assessment of toxic chemi...
3    i dont know if intense text sex the medication...
4    #imaginedragons singer @danreynolds opens up a...
Name: message, dtype: object

In [23]:
type(result)

pandas.core.series.Series

In [24]:
data_t=result

In [25]:
#lowercase
data_t = data_t.str.lower()
#Remove urls
data_t= data_t.str.replace(r'(http.*) |(http.*)$|\n', "",)
#Remove twitter handles
data_t = data_t.str.replace(r"@\\w+", "")
#remove htmls
data_t = data_t.str.replace(r'<.*?>', "")
#Remove citations
data_t = data_t.str.replace(r'@[a-zA-Z0-9]*', "")

#remove _
#data_t = data_t.str.replace(r'\_+',"")

In [28]:
#Start of sentiment analysis

In [71]:
analyzer = SentimentIntensityAnalyzer()

In [80]:
analyzer.polarity_scores(data_t[190])

{'compound': -0.0772, 'neg': 0.071, 'neu': 0.929, 'pos': 0.0}

In [106]:
res= pd.DataFrame( index=range(0,len(data_t)),columns = {'SentimentVader'} )

In [107]:
for i in range(len(data_t)):
    vs = analyzer.polarity_scores(data_t.values[i])
    if ((vs['compound']==0)):
        res.values[i]= 'neu' 
    elif ((vs['compound'] < 0)):
        res.values[i]= 'neg'
    else:
        res.values[i]= 'pos'
    

In [108]:
res.SentimentVader

0      neg
1      neu
2      neu
3      neg
4      neg
5      neu
6      neg
7      neg
8      pos
9      neu
10     neu
11     neu
12     neu
13     neg
14     neu
15     neu
16     neg
17     neg
18     neu
19     neg
20     pos
21     neu
22     neg
23     neg
24     neu
25     pos
26     neu
27     pos
28     neu
29     pos
      ... 
935    pos
936    pos
937    pos
938    pos
939    pos
940    neu
941    neu
942    pos
943    pos
944    neg
945    pos
946    pos
947    neu
948    pos
949    pos
950    pos
951    pos
952    neg
953    neg
954    pos
955    pos
956    pos
957    pos
958    pos
959    neg
960    neg
961    neu
962    pos
963    pos
964    neu
Name: SentimentVader, dtype: object

In [40]:
data_t.head(10)

0    #llbite ankylosing spondylitis - have (in date...
1    #as 3 things people with ankylosing spondyliti...
2    working group on the assessment of toxic chemi...
3    i dont know if intense text sex the medication...
4    #imaginedragons singer  opens up about his str...
5    chinese medicine cure ankylosing spondylitis c...
6    pain relief for patients with rheumatoid arthr...
7    suffering from #ankylosingspondylitis? check o...
8    herself goodwill newsletter significant other ...
9    how they did it: 5 people with ankylosing spon...
Name: message, dtype: object

In [109]:
from textblob import TextBlob

In [110]:
final=pd.concat([data_t, res], axis=1)
final=pd.concat([final, data_s], axis=1)

In [111]:
res5= pd.DataFrame( index=range(0,len(data_t)),columns = {'new_sent'} )
res5[(final.sentiment==u'2')] = 'neg'
res5[(final.sentiment==u'1')] = 'neg'
res5[(final['sentiment']==u'3')] = 'pos'
res5[(final['sentiment']==u'4')] = 'pos'
res5[(final['sentiment']==u'N')] = 'neu'
final=pd.concat([final, res5], axis=2)

In [112]:
final

message SentimentVader  \
0    #llbite ankylosing spondylitis - have (in date...            neg   
1    #as 3 things people with ankylosing spondyliti...            neu   
2    working group on the assessment of toxic chemi...            neu   
3    i dont know if intense text sex the medication...            neg   
4    #imaginedragons singer  opens up about his str...            neg   
5    chinese medicine cure ankylosing spondylitis c...            neu   
6    pain relief for patients with rheumatoid arthr...            neg   
7    suffering from #ankylosingspondylitis? check o...            neg   
8    herself goodwill newsletter significant other ...            pos   
9    how they did it: 5 people with ankylosing spon...            neu   
10   imagine dragoons singer breaks silence about a...            neu   
11     the progression old fart ankylosing spondylitis            neu   
12                              real time -or- retweet            neu   
13   imagine dragons?dan reynolds speaks out about ...            neg   
14   imagine dragons lead singer, dan reynolds, and...            neu   
15   chinese traditional medicine ankylosing spondy...            neu   
16   imagine dragons?dan reynolds speaks out about ...            neg   
17   imagine dragons' dan reynolds speaks out about...            neg   
18   imagine dragons' dan reynolds breaks his silen...            neu   
19   imagine dragon's dan reynolds breaks his silen...            neg   
20   great to be back at the gym today after (in da...            pos   
21   ankylosing spondylitis mom: when your diploma ...            neu   
22     i saw ape sh** -or- another subject used the...            neg   
23   . singer  opens up about his struggle with #an...            neg   
24                     what is #ankylosingspondylitis?            neu   
25   how they did it: 5 people with ankylosing spon...            pos   
26   252.???????????casset?c - cystic fibrosisa - a...            neu   
27   via  spokesman dan reynolds will help bring aw...            pos   
28   ankylosing spondylitis... it's (in dates) ante...            neu   
29   my boyfriend ben is running major cytogenetic ...            pos   
..                                                 ...            ...   
935  thanks _ni_tweets   _group   _advice  and  for...            pos   
936  amgen, inc. $amgn rating increased to strong-b...            pos   
937  this is great to see - #amgen staff member jam...            pos   
938  novartis: study shows copycat works just ape s...            pos   
939  is amgen losing confidence in novartis-partner...            pos   
940  #biotech: 3 things to focus omni nocte (every ...            neu   
941  #360wisenews : earnings preview: what to expec...            neu   
942  thanks for the post and significant other glad...            pos   
943  (in dates) ante huge thank you to all our spon...            pos   
944  the unholy joan &amp; all leinster house are s...            neg   
945  amgen to co-promote migraine med erenumab with...            pos   
946  "i want to take ape sh** -or- another subject ...            pos   
947  amgen, inc. $amgn receives $187.99 consensus p...            neu   
948  afternoon with more interesting talks in #anti...            pos   
949  congratulations to katie aney winner old fart ...            pos   
950  amgen, inc. $amgn shares bought by weaver coun...            pos   
951  #hallmarkies  thank you for sponsoring quality...            pos   
952  whatever know why there are missing gardai-the...            neg   
953  already at war over pcsk9, drug giants go to c...            neg   
954   why would (in dates) ante drug co like amgen ...            pos   
955  high school students reveal how whatever can b...            pos   
956  amgen files for united states approval old far...            pos   
957  teachers retirement system old fart the state ...            pos   
958  dears,anyone have any idea 

In [113]:
from sklearn.metrics import confusion_matrix

In [114]:
print(confusion_matrix(final.new_sent, final.SentimentVader).transpose())

[[147  44  43]
 [104 126 103]
 [ 74  98 226]]
